### ISSUE TITLE
remove left peek width

### ISSUE THREAD

**Issue by cihangulx** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#35]
how can i set only left peek width 0, change to cell origin not working.

**Comment by MaherKSantina** [comment]
Thank you @cihangulx for opening this issue. Having a variable peeking width for different cells is not currently supported. Honestly i don't have plans to support this because it will make the implementation a bit complicated. If you have any ideas/examples on how to update the current implementation to support that I'm happy to look at them!
