### ISSUE TITLE
Support Dynamic Width?

### ISSUE THREAD

**Issue by HePingLaoSan** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#44]
Great Thanks to your repo , do you have plan to support dynamic cell width please? thanks again

**Comment by MaherKSantina** [comment]
Thank you so much @HePingLaoSan!
So you mean that you want to specify a specific width for each cell and let the peeking fill the remaining space? That would be something interesting to have, although I don't have 100% vision of how it can be achieved. But it's definitely something nice to have and worth considering!
It might take me a while to implement this because I'm a bit busy at work. In the meantime feel free to make a PR if you have the chance to do it! I'd be happy to help you out with the current implementation so you can have an idea about what's going on

**Comment by MaherKSantina** [comment]
Hello @HePingLaoSan , I'm really sorry but I have to close this issue for now as it's stale. Feel free to open another issue when you have more information! 

Thanks for the contribution and interest in this repo! 👍
