### ISSUE TITLE
Clip last item

### ISSUE THREAD

**Issue by Kendokai** [MaherKSantina/MSPeekCollectionViewDelegateImplementation#50]
![Simulator Screen Shot - iPhone 11 - 2019-11-06 at 15 51 32](https://user-images.githubusercontent.com/8243358/68283099-85a8dd00-00ad-11ea-9544-bc057f068865.png)

I've followed instruction but when render, I got the last item clipped.

**Comment by MaherKSantina** [comment]
Thanks @Kendokai for raising this issue and for your interest in this library! I'm really sorry it took me some time to reply back I got caught up in things. Can you please share with me some extra information such as:
- Device
- OS
- Number of items in the collection
- Is the collection view in a table view?

**Comment by mpmartimbianco** [comment]
Hi, I'm enjoying this library too and facing this same issue, it occurs at my iphone 6s as well as at all simulator in my machine.

I'm using ios 13 on device, and developing for 11
I have 4 items, but more items I have bigger this wrong offset
This problem happens with the collection on the root view as well as inside a scrollview on my case

**Comment by MaherKSantina** [comment]
Hello @mpmartimbianco! Thank you so much for your interest in this library and thank you for confirming the details of the issue! I can say now it's time to re-implement the layout using a custom collection view layout instead of trying to use the default one! Clearly it's causing some issues! I'm currently working on a new version which implements a peeking layout and theoretically it should be more flexible than this one. I'll keep you guys posted about it!

**Comment by MaherKSantina** [comment]
Hello @mpmartimbianco and @Kendokai ! I wanted to let you know that I re-developed the library using a custom collection view layout and a paging component! I think this will solve your issues related to the clipping and will provide a better peeking/paging experience overall! There's a bit of change that you guys need to do in the code to support the new behavior but it shouldn't be that much. Here's the release
https://github.com/MaherKSantina/MSPeekCollectionViewDelegateImplementation/releases/tag/3.0.0

Also, you can take a look at the README.md if you need any help with the migration

Thank you so much for raising this issue and being interested in this library! ❤️

**Comment by mpmartimbianco** [comment]
hello @MaherKSantina thank you for the reply and support, I'm using now the 3.0 version, it is much better because it clears my view controller. But to be honest I still have this issue. Just downloading the MSPeekCollectionViewDelegateImplementation-3.0.0.zip and testing on it, you probably will see a issue when set a high value to cell peek width (cell spacing is lower then cell peek width)

Can you confirm it to me?

Otherwise I can do something wrong so setup your component

**Comment by MaherKSantina** [comment]
Hello @mpmartimbianco , I'm really sorry you're still experiencing some issues. Can you please show me the piece of code where you are implementing the peeking?

**Comment by MaherKSantina** [comment]
Hello @mpmartimbianco , I was able to reproduce this issue. I will work on a fix for it. Thanks for spotting it!

**Comment by MaherKSantina** [comment]
@mpmartimbianco thank you for raising this issue! I was able to issue a fix for your problem and it's now in v 3.0.3 from the library. 
Feel free to re-open this issue if the problem is still there.

Have a great day!

**Comment by mpmartimbianco** [comment]
@MaherKSantina hello, sorry for the late reply, I was away from home this days. Thank ypu again, I will test it new version

**Comment by MaherKSantina** [comment]
No problem @mpmartimbianco! Hope you had a great time! Sure thing test it and let me know if you jump into any issues 👍
